### PR TITLE
chore: fix-web-example

### PR DESCRIPTION
**Pull request by npty**
## Changes
- Update package `@axelar-network/axelar-gmp-sdk-solidity` to version `3.2.1`
- Update package `@axelar-network/axelar-local-dev` to version `1.4.2`
- Update package `hardhat` to version `2.13.0`
- Update `contracts/nft-linker/ExampleProxy` to extends from `InitProxy` instead of `BaseProxy`.

### CODE REVIEW

**Comment by StephenFluin** [comment]
Still getting errors, currently with `npm run deploy` from the `examples-web` folder. I ran npm ci in both the root and `examples-web`.  

```
$ npm run deploy

> axelar-example-web@0.1.0 deploy
> run-s contracts:build contracts:generate contracts:deploy


> axelar-example-web@0.1.0 contracts:build
> hardhat compile

Compiled 32 Solidity files successfully

> axelar-example-web@0.1.0 contracts:generate
> typechain --target ethers-v5 --out-dir src/types/contracts artifacts/*[!build-info]/**/*[!dbg].json

Successfully generated 77 typings!

> axelar-example-web@0.1.0 contracts:deploy
> ts-node scripts/deploy-contracts.ts

npm run dev
/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:58
    return !!(value.toHexString);
                    ^
TypeError: Cannot read properties of undefined (reading 'toHexString')
    at isHexable (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:58:21)
    at hexlify (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:228:9)
    at new SigningKey (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/signing-key/src.ts/index.ts:35:51)
    at new Wallet (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/wallet/src.ts/index.ts:87:36)
    at Object.<anonymous> (/home/stephen/workspace/axelar-examples/examples-web/scripts/deploy-contracts.ts:12:16)
    at Module._compile (node:internal/modules/cjs/loader:1155:14)
    at Module.m._compile (/home/stephen/workspace/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1597:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
    at Object.require.extensions.<computed> [as .ts] (/home/stephen/workspace/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1600:12)
    at Module.load (node:internal/modules/cjs/loader:1033:32)
ERROR: "contracts:deploy" exited with 1.
```

**Comment by FriendlyLifeguard** [comment]
Also getting the same error as Stephen.

**Comment by StephenFluin** [comment]
Added https://github.com/axelarnetwork/axelar-examples/issues/107

**Comment by npty** [comment]
> Still getting errors, currently with `npm run deploy` from the `examples-web` folder. I ran npm ci in both the root and `examples-web`.
> 
> ```
> $ npm run deploy
> 
> > axelar-example-web@0.1.0 deploy
> > run-s contracts:build contracts:generate contracts:deploy
> 
> 
> > axelar-example-web@0.1.0 contracts:build
> > hardhat compile
> 
> Compiled 32 Solidity files successfully
> 
> > axelar-example-web@0.1.0 contracts:generate
> > typechain --target ethers-v5 --out-dir src/types/contracts artifacts/*[!build-info]/**/*[!dbg].json
> 
> Successfully generated 77 typings!
> 
> > axelar-example-web@0.1.0 contracts:deploy
> > ts-node scripts/deploy-contracts.ts
> 
> npm run dev
> /home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:58
>     return !!(value.toHexString);
>                     ^
> TypeError: Cannot read properties of undefined (reading 'toHexString')
>     at isHexable (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:58:21)
>     at hexlify (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/bytes/src.ts/index.ts:228:9)
>     at new SigningKey (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/signing-key/src.ts/index.ts:35:51)
>     at new Wallet (/home/stephen/workspace/axelar-examples/examples-web/node_modules/@ethersproject/wallet/src.ts/index.ts:87:36)
>     at Object.<anonymous> (/home/stephen/workspace/axelar-examples/examples-web/scripts/deploy-contracts.ts:12:16)
>     at Module._compile (node:internal/modules/cjs/loader:1155:14)
>     at Module.m._compile (/home/stephen/workspace/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1597:23)
>     at Module._extensions..js (node:internal/modules/cjs/loader:1209:10)
>     at Object.require.extensions.<computed> [as .ts] (/home/stephen/workspace/axelar-examples/examples-web/node_modules/ts-node/src/index.ts:1600:12)
>     at Module.load (node:internal/modules/cjs/loader:1033:32)
> ERROR: "contracts:deploy" exited with 1.
> ```

The instruction in `examples-web/README.md` is confused. I'll improve it to make it more clear.

It seems like the variable `NEXT_PUBLIC_EVM_PRIVATE_KEY` in the `examples-web/.env` file is missing. This could be done automatically with `npm run setup`. It will copy the private key and mnemonic from `.env` to `examples-web/.env`

**Comment by npty** [comment]
> Also getting the same error as Stephen and when I try to access the nft-linker page, I am confronted with this error.
> 
> Screenshot 2023-04-01 at 2 11 24 PM (2)

Thanks for your feedback! I think that's because the contracts are failed to deployed. You can verify that by checking if the `nftLinker` key exists in `chain-config/local.json`.

**Comment by npty** [comment]
@StephenFluin could you try pull the new update and follow the instruction [here](https://github.com/axelarnetwork/axelar-examples/tree/chore/fix-web-example/examples-web#run-web-examples-locally)?

**Comment by StephenFluin** [comment]
@npty Following new steps. We should add `npm ci` to the steps, but I ran this in both folders. 

Ran into this error:
```
$ npm run setup

> axelar-example-web@0.1.0 setup
> ts-node scripts/setup.ts

/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:6
  const rootEnvLines = rootEnv.split('\n');
                               ^
TypeError: rootEnv.split is not a function
    at getEnvValue (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:6:32)
    at /home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:14:25
    at step (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:33:23)
    at Object.next (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:14:53)
    at /home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:4:12)
    at main (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:51:12)
    at Object.<anonymous> (/home/stephen/workspace/axelar/axelar-examples/examples-web/scripts/setup.ts:28:1)
    at Module._compile (node:internal/modules/cjs/loader:1103:14)
```

**Comment by StephenFluin** [comment]
Found the problem. ReadFileSync gives you a `Buffer` not a string. YOu have to cast it. We should get rid of the `any` in the function signature and TypeScript would have caught this. Great argument for TypeScript, :).

**Comment by StephenFluin** [comment]
Made it past that error with `  const rootEnv = fs.readFileSync(rootEnvPath).toString();`. Got this new error on deploy.

```
$ npm run deploy

> axelar-example-web@0.1.0 deploy
> run-s contracts:build contracts:generate contracts:deploy


> axelar-example-web@0.1.0 contracts:build
> hardhat compile

Nothing to compile

> axelar-example-web@0.1.0 contracts:generate
> typechain --target ethers-v5 --out-dir src/types/contracts artifacts/*[!build-info]/**/*[!dbg].json

Successfully generated 77 typings!

> axelar-example-web@0.1.0 contracts:deploy
> ts-node scripts/deploy-contracts.ts

/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/logger/src.ts/index.ts:261
        const error: any = new Error(message);
                           ^
Error: insufficient funds for intrinsic transaction cost [ See: https://links.ethers.org/v5-errors-INSUFFICIENT_FUNDS ] (error={"reason":"processing response error","code":"SERVER_ERROR","body":"{\"id\":53,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"insufficient funds for gas * price + value\",\"stack\":\"Error: insufficient funds for gas * price + value\\n    at TransactionPool.prepareTransaction (/home/stephen/workspace/hbc/axelar-examples/node_modules/ganache/dist/node/1.js:2:167249)\",\"code\":-32003}}","error":{"code":-32003},"requestBody":"{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f905838209c7808459682f0084665c48bc83045f3c8080b9052860c060405234801561001057600080fd5b506040516104e83803806104e883398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a05161042f6100b9600039600060a201526000610155015261042f6000f3fe60806040526004361061001e5760003560e01c80630eabeffe14610023575b600080fd5b610036610031366004610216565b610038565b005b6000828260405160200161004d9291906102d9565b60408051601f1981840301815291905290503415610118576040517f0c93e3bb00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690630c93e3bb9034906100e59030908c908c908c908c908a903390600401610342565b6000604051808303818588803b1580156100fe57600080fd5b505af1158015610112573d6000803e3d6000fd5b50505050505b6040517f1c92115f00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690631c92115f90610192908a908a908a908a9088906004016103b2565b600060405180830381600087803b1580156101ac57600080fd5b505af11580156101c0573d6000803e3d6000fd5b5050505050505050505050565b60008083601f8401126101df57600080fd5b50813567ffffffffffffffff8111156101f757600080fd5b60208301915083602082850101111561020f57600080fd5b9250929050565b6000806000806000806060878903121561022f57600080fd5b863567ffffffffffffffff8082111561024757600080fd5b6102538a838b016101cd565b9098509650602089013591508082111561026c57600080fd5b6102788a838b016101cd565b9096509450604089013591508082111561029157600080fd5b5061029e89828a016101cd565b979a9699509497509295939492505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b6020815260006102ed6020830184866102b0565b949350505050565b6000815180845260005b8181101561031b576020818501810151868301820152016102ff565b8181111561032d576000602083870101525b50601f01601f19169290920160200192915050565b600073ffffffffffffffffffffffffffffffffffffffff808a16835260a0602084015261037360a08401898b6102b0565b838103604085015261038681888a6102b0565b9050838103606085015261039a81876102f5565b92505080841660808401525098975050505050505050565b6060815260006103c66060830187896102b0565b82810360208401526103d98186886102b0565b905082810360408401526103ed81856102f5565b9897505050505050505056fea264697066735822122021ae581e2f64e482bd9637fd73e7a62a0d757e05292aae6172870f565256ae3164736f6c63430008090033000000000000000000000000013459ec3e8aeced878c5c4bffe126a366cd19e900000000000000000000000028f8b50e1be6152da35e923602a2641491e71ed8c080a0e6afedb6abd6884d78f76716425535e8a61f565911e0f01147f8d30b609fc664a001cfd937aef566560fb7f15526c020154c6e96687993cda022f674883b21b095\"],\"id\":53,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://localhost:8500/3"}, method="sendTransaction", transaction="0x02f905838209c7808459682f0084665c48bc83045f3c8080b9052860c060405234801561001057600080fd5b506040516104e83803806104e883398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a05161042f6100b9600039600060a201526000610155015261042f6000f3fe60806040526004361061001e5760003560e01c80630eabeffe14610023575b600080fd5b610036610031366004610216565b610038565b005b6000828260405160200161004d9291906102d9565b60408051601f1981840301815291905290503415610118576040517f0c93e3bb00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690630c93e3bb9034906100e59030908c908c908c908c908a903390600401610342565b6000604051808303818588803b1580156100fe57600080fd5b505af1158015610112573d6000803e3d6000fd5b50505050505b6040517f1c92115f00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690631c92115f90610192908a908a908a908a9088906004016103b2565b600060405180830381600087803b1580156101ac57600080fd5b505af11580156101c0573d6000803e3d6000fd5b5050505050505050505050565b60008083601f8401126101df57600080fd5b50813567ffffffffffffffff8111156101f757600080fd5b60208301915083602082850101111561020f57600080fd5b9250929050565b6000806000806000806060878903121561022f57600080fd5b863567ffffffffffffffff8082111561024757600080fd5b6102538a838b016101cd565b9098509650602089013591508082111561026c57600080fd5b6102788a838b016101cd565b9096509450604089013591508082111561029157600080fd5b5061029e89828a016101cd565b979a9699509497509295939492505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b6020815260006102ed6020830184866102b0565b949350505050565b6000815180845260005b8181101561031b576020818501810151868301820152016102ff565b8181111561032d576000602083870101525b50601f01601f19169290920160200192915050565b600073ffffffffffffffffffffffffffffffffffffffff808a16835260a0602084015261037360a08401898b6102b0565b838103604085015261038681888a6102b0565b9050838103606085015261039a81876102f5565b92505080841660808401525098975050505050505050565b6060815260006103c66060830187896102b0565b82810360208401526103d98186886102b0565b905082810360408401526103ed81856102f5565b9897505050505050505056fea264697066735822122021ae581e2f64e482bd9637fd73e7a62a0d757e05292aae6172870f565256ae3164736f6c63430008090033000000000000000000000000013459ec3e8aeced878c5c4bffe126a366cd19e900000000000000000000000028f8b50e1be6152da35e923602a2641491e71ed8c080a0e6afedb6abd6884d78f76716425535e8a61f565911e0f01147f8d30b609fc664a001cfd937aef566560fb7f15526c020154c6e96687993cda022f674883b21b095", code=INSUFFICIENT_FUNDS, version=providers/5.6.8)
    at Logger.makeError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at checkError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:98:16)
    at JsonRpcProvider.<anonymous> (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:603:20)
    at step (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:48:23)
    at Object.throw (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:29:53)
    at rejected (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/lib/json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'insufficient funds for intrinsic transaction cost',
  code: 'INSUFFICIENT_FUNDS',
  error: Error: processing response error (body="{\"id\":53,\"jsonrpc\":\"2.0\",\"error\":{\"message\":\"insufficient funds for gas * price + value\",\"stack\":\"Error: insufficient funds for gas * price + value\\n    at TransactionPool.prepareTransaction (/home/stephen/workspace/hbc/axelar-examples/node_modules/ganache/dist/node/1.js:2:167249)\",\"code\":-32003}}", error={"code":-32003}, requestBody="{\"method\":\"eth_sendRawTransaction\",\"params\":[\"0x02f905838209c7808459682f0084665c48bc83045f3c8080b9052860c060405234801561001057600080fd5b506040516104e83803806104e883398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a05161042f6100b9600039600060a201526000610155015261042f6000f3fe60806040526004361061001e5760003560e01c80630eabeffe14610023575b600080fd5b610036610031366004610216565b610038565b005b6000828260405160200161004d9291906102d9565b60408051601f1981840301815291905290503415610118576040517f0c93e3bb00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690630c93e3bb9034906100e59030908c908c908c908c908a903390600401610342565b6000604051808303818588803b1580156100fe57600080fd5b505af1158015610112573d6000803e3d6000fd5b50505050505b6040517f1c92115f00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690631c92115f90610192908a908a908a908a9088906004016103b2565b600060405180830381600087803b1580156101ac57600080fd5b505af11580156101c0573d6000803e3d6000fd5b5050505050505050505050565b60008083601f8401126101df57600080fd5b50813567ffffffffffffffff8111156101f757600080fd5b60208301915083602082850101111561020f57600080fd5b9250929050565b6000806000806000806060878903121561022f57600080fd5b863567ffffffffffffffff8082111561024757600080fd5b6102538a838b016101cd565b9098509650602089013591508082111561026c57600080fd5b6102788a838b016101cd565b9096509450604089013591508082111561029157600080fd5b5061029e89828a016101cd565b979a9699509497509295939492505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b6020815260006102ed6020830184866102b0565b949350505050565b6000815180845260005b8181101561031b576020818501810151868301820152016102ff565b8181111561032d576000602083870101525b50601f01601f19169290920160200192915050565b600073ffffffffffffffffffffffffffffffffffffffff808a16835260a0602084015261037360a08401898b6102b0565b838103604085015261038681888a6102b0565b9050838103606085015261039a81876102f5565b92505080841660808401525098975050505050505050565b6060815260006103c66060830187896102b0565b82810360208401526103d98186886102b0565b905082810360408401526103ed81856102f5565b9897505050505050505056fea264697066735822122021ae581e2f64e482bd9637fd73e7a62a0d757e05292aae6172870f565256ae3164736f6c63430008090033000000000000000000000000013459ec3e8aeced878c5c4bffe126a366cd19e900000000000000000000000028f8b50e1be6152da35e923602a2641491e71ed8c080a0e6afedb6abd6884d78f76716425535e8a61f565911e0f01147f8d30b609fc664a001cfd937aef566560fb7f15526c020154c6e96687993cda022f674883b21b095\"],\"id\":53,\"jsonrpc\":\"2.0\"}", requestMethod="POST", url="http://localhost:8500/3", code=SERVER_ERROR, version=web/5.6.1)
      at Logger.makeError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
      at Logger.throwError (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
      at /home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/src.ts/index.ts:329:28
      at step (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:33:23)
      at Object.next (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:14:53)
      at fulfilled (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:5:58)
      at processTicksAndRejections (node:internal/process/task_queues:96:5) {
    reason: 'processing response error',
    code: 'SERVER_ERROR',
    body: '{"id":53,"jsonrpc":"2.0","error":{"message":"insufficient funds for gas * price + value","stack":"Error: insufficient funds for gas * price + value\\n    at TransactionPool.prepareTransaction (/home/stephen/workspace/hbc/axelar-examples/node_modules/ganache/dist/node/1.js:2:167249)","code":-32003}}',
    error: Error: insufficient funds for gas * price + value
        at getResult (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/providers/src.ts/json-rpc-provider.ts:142:28)
        at processJsonFunc (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/src.ts/index.ts:371:22)
        at /home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/src.ts/index.ts:308:42
        at step (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:33:23)
        at Object.next (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:14:53)
        at fulfilled (/home/stephen/workspace/axelar/axelar-examples/examples-web/node_modules/@ethersproject/web/lib/index.js:5:58)
        at processTicksAndRejections (node:internal/process/task_queues:96:5) {
      code: -32003,
      data: undefined
    },
    requestBody: '{"method":"eth_sendRawTransaction","params":["0x02f905838209c7808459682f0084665c48bc83045f3c8080b9052860c060405234801561001057600080fd5b506040516104e83803806104e883398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a05161042f6100b9600039600060a201526000610155015261042f6000f3fe60806040526004361061001e5760003560e01c80630eabeffe14610023575b600080fd5b610036610031366004610216565b610038565b005b6000828260405160200161004d9291906102d9565b60408051601f1981840301815291905290503415610118576040517f0c93e3bb00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690630c93e3bb9034906100e59030908c908c908c908c908a903390600401610342565b6000604051808303818588803b1580156100fe57600080fd5b505af1158015610112573d6000803e3d6000fd5b50505050505b6040517f1c92115f00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690631c92115f90610192908a908a908a908a9088906004016103b2565b600060405180830381600087803b1580156101ac57600080fd5b505af11580156101c0573d6000803e3d6000fd5b5050505050505050505050565b60008083601f8401126101df57600080fd5b50813567ffffffffffffffff8111156101f757600080fd5b60208301915083602082850101111561020f57600080fd5b9250929050565b6000806000806000806060878903121561022f57600080fd5b863567ffffffffffffffff8082111561024757600080fd5b6102538a838b016101cd565b9098509650602089013591508082111561026c57600080fd5b6102788a838b016101cd565b9096509450604089013591508082111561029157600080fd5b5061029e89828a016101cd565b979a9699509497509295939492505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b6020815260006102ed6020830184866102b0565b949350505050565b6000815180845260005b8181101561031b576020818501810151868301820152016102ff565b8181111561032d576000602083870101525b50601f01601f19169290920160200192915050565b600073ffffffffffffffffffffffffffffffffffffffff808a16835260a0602084015261037360a08401898b6102b0565b838103604085015261038681888a6102b0565b9050838103606085015261039a81876102f5565b92505080841660808401525098975050505050505050565b6060815260006103c66060830187896102b0565b82810360208401526103d98186886102b0565b905082810360408401526103ed81856102f5565b9897505050505050505056fea264697066735822122021ae581e2f64e482bd9637fd73e7a62a0d757e05292aae6172870f565256ae3164736f6c63430008090033000000000000000000000000013459ec3e8aeced878c5c4bffe126a366cd19e900000000000000000000000028f8b50e1be6152da35e923602a2641491e71ed8c080a0e6afedb6abd6884d78f76716425535e8a61f565911e0f01147f8d30b609fc664a001cfd937aef566560fb7f15526c020154c6e96687993cda022f674883b21b095"],"id":53,"jsonrpc":"2.0"}',
    requestMethod: 'POST',
    url: 'http://localhost:8500/3'
  },
  method: 'sendTransaction',
  transaction: {
    type: 2,
    chainId: 2503,
    nonce: 0,
    maxPriorityFeePerGas: BigNumber { _hex: '0x59682f00', _isBigNumber: true },
    maxFeePerGas: BigNumber { _hex: '0x665c48bc', _isBigNumber: true },
    gasPrice: null,
    gasLimit: BigNumber { _hex: '0x045f3c', _isBigNumber: true },
    to: null,
    value: BigNumber { _hex: '0x00', _isBigNumber: true },
    data: '0x60c060405234801561001057600080fd5b506040516104e83803806104e883398101604081905261002f91610062565b6001600160a01b039182166080521660a052610095565b80516001600160a01b038116811461005d57600080fd5b919050565b6000806040838503121561007557600080fd5b61007e83610046565b915061008c60208401610046565b90509250929050565b60805160a05161042f6100b9600039600060a201526000610155015261042f6000f3fe60806040526004361061001e5760003560e01c80630eabeffe14610023575b600080fd5b610036610031366004610216565b610038565b005b6000828260405160200161004d9291906102d9565b60408051601f1981840301815291905290503415610118576040517f0c93e3bb00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690630c93e3bb9034906100e59030908c908c908c908c908a903390600401610342565b6000604051808303818588803b1580156100fe57600080fd5b505af1158015610112573d6000803e3d6000fd5b50505050505b6040517f1c92115f00000000000000000000000000000000000000000000000000000000815273ffffffffffffffffffffffffffffffffffffffff7f00000000000000000000000000000000000000000000000000000000000000001690631c92115f90610192908a908a908a908a9088906004016103b2565b600060405180830381600087803b1580156101ac57600080fd5b505af11580156101c0573d6000803e3d6000fd5b5050505050505050505050565b60008083601f8401126101df57600080fd5b50813567ffffffffffffffff8111156101f757600080fd5b60208301915083602082850101111561020f57600080fd5b9250929050565b6000806000806000806060878903121561022f57600080fd5b863567ffffffffffffffff8082111561024757600080fd5b6102538a838b016101cd565b9098509650602089013591508082111561026c57600080fd5b6102788a838b016101cd565b9096509450604089013591508082111561029157600080fd5b5061029e89828a016101cd565b979a9699509497509295939492505050565b81835281816020850137506000828201602090810191909152601f909101601f19169091010190565b6020815260006102ed6020830184866102b0565b949350505050565b6000815180845260005b8181101561031b576020818501810151868301820152016102ff565b8181111561032d576000602083870101525b50601f01601f19169290920160200192915050565b600073ffffffffffffffffffffffffffffffffffffffff808a16835260a0602084015261037360a08401898b6102b0565b838103604085015261038681888a6102b0565b9050838103606085015261039a81876102f5565b92505080841660808401525098975050505050505050565b6060815260006103c66060830187896102b0565b82810360208401526103d98186886102b0565b905082810360408401526103ed81856102f5565b9897505050505050505056fea264697066735822122021ae581e2f64e482bd9637fd73e7a62a0d757e05292aae6172870f565256ae3164736f6c63430008090033000000000000000000000000013459ec3e8aeced878c5c4bffe126a366cd19e900000000000000000000000028f8b50e1be6152da35e923602a2641491e71ed8',
    accessList: [],
    hash: '0x5db0f18537ebc2f0323286671f5cb0142e0d74ba65d981e7dcc3f85c2c401240',
    v: 0,
    r: '0xe6afedb6abd6884d78f76716425535e8a61f565911e0f01147f8d30b609fc664',
    s: '0x01cfd937aef566560fb7f15526c020154c6e96687993cda022f674883b21b095',
    from: '0xB1759Ce16aB6eBe4C13CDa19a9980F96355e295E',
    confirmations: 0
  },
  transactionHash: '0x5db0f18537ebc2f0323286671f5cb0142e0d74ba65d981e7dcc3f85c2c401240'
}
ERROR: "contracts:deploy" exited with 1.
```

**Comment by npty** [comment]
@StephenFluin Sorry for not checking that before pinging you to review 🙇🏻 
Fixed two issues:
- Convert `buffer` to `string` after `readFileSync` function.
- Add `npm ci` to `README.md`

For the insufficient funds issue, it happens because your wallet doesn't have enough fund. Can you check if the private key in `examples-web/.env` and `.env` are the same? If they are the same private key, your wallet should be funded when running `npm run start`.

**Review by StephenFluin — APPROVED** [review]

**Comment by npty** [comment]
> Thanks!!! It took me some time to find this PR, and finally I can get it to work! :)

Nice find! Congratulation! 🚀

**Pull request merged**
